# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de4a60811c183fe2913da0ac09df0fa375d51c047bd21bb97429a4fa4f6f868ab670532058e802d4ea3d41b619795ec79a654503b90dbbcc5285016f840d08dc

test:
  secret_key_base: 9a75a5d89cfd23465f4fb9285b0667ac0b4e58ffa9cd429f9bd458f0033ac73485be155e8afadd1f5d2212964a82ce4b59c7914ae4c445d4480f2d8e59c971b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
